version: "3"

tasks:
  api:
    cmds:
      - cd backend/app/api/ && swag fmt
      - cd backend/app/api/ && swag init --dir=./,../../internal,../../pkgs,../../ent
      # - |
      #   npx swagger-typescript-api \
      #     --path ./backend/app/api/docs/swagger.json \
      #     --output ./client/auto-client \
      #     --module-name-first-tag \
      #     --modular
      - cd backend && go run ./app/api/ {{.CLI_ARGS}}
    silent: false
    sources:
      - ./backend/**/*.go

  api:build:
    cmds:
      - cd backend && go build ./app/api/
    silent: true

  api:test:
    cmds:
      - cd backend && go test ./app/api/
    silent: true

  api:coverage:
    cmds:
      - cd backend && go test -race -coverprofile=coverage.out -covermode=atomic ./app/... ./internal/... ./pkgs/... -v -cover
    silent: true

  test:integration:
    cmds:
      - cd backend && go build ./app/api
      - backend/api &
      - sleep 5
      - cd frontend && pnpm run test:ci
    silent: true

  docker:build:
    cmds:
      - cd backend && docker-compose up --build
    silent: true

  generate:types:
    cmds:
      - cd backend && go run ./app/generator
    silent: true
