version: "3"

tasks:
  generate:
    cmds:
      - |
        cd backend && ent generate ./ent/schema \
          --template=ent/schema/templates/stringer.tmpl \
          --template=ent/schema/templates/has_id.tmpl
      - cd backend/app/api/ && swag fmt
      - cd backend/app/api/ && swag init --dir=./,../../internal,../../pkgs
      - |
        npx swagger-typescript-api \
          --no-client \
          --clean-output \
          --modular \
          --path ./backend/app/api/docs/swagger.json \
          --output ./frontend/lib/api/types

        # Output cleanup for the generated types
        #   1. Remove the prefix `Types` from each type generated
        #   2. Remove the ?: from the type definition since types are not properly annotated in the swagger.json

        python3 ./scripts/process-types.py ./frontend/lib/api/types/data-contracts.ts
  api:
    cmds:
      - task: generate
      - cd backend && go run ./app/api/ {{.CLI_ARGS}}
    silent: false
    sources:
      - ./backend/**/*.go

  api:build:
    cmds:
      - cd backend && go build ./app/api/
    silent: true

  api:test:
    cmds:
      - cd backend && go test ./app/api/
    silent: true

  api:coverage:
    cmds:
      - cd backend && go test -race -coverprofile=coverage.out -covermode=atomic ./app/... ./internal/... ./pkgs/... -v -cover
    silent: true

  test:ci:
    cmds:
      - cd backend && go build ./app/api
      - backend/api &
      - sleep 5
      - cd frontend && pnpm run test:ci
    silent: true

  docker:build:
    cmds:
      - cd backend && docker-compose up --build
    silent: true

  generate:types:
    cmds:
      - cd backend && go run ./app/generator
    silent: true
