run:
  timeout: 10m
  skip-dirs:
    - internal/data/ent.*
linters-settings:
  goconst:
    min-len: 5
    min-occurrences: 5
  exhaustive:
    default-signifies-exhaustive: true
  revive:
    ignore-generated-header: false
    severity: warning
    confidence: 3
  depguard:
    rules:
      main:
        deny:
          - pkg: io/util
            desc: |
              Deprecated: As of Go 1.16, the same functionality is now provided by
              package io or package os, and those implementations should be
              preferred in new code. See the specific function documentation for
              details.
  gocritic:
    enabled-checks:
      - ruleguard
  testifylint:
    enable-all: true
  tagalign:
    order:
      - json
      - schema
      - yaml
      - yml
      - toml
      - validate
linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - stylecheck
    - tagalign
    - testifylint
    - typecheck
    - typecheck
    - unconvert
    - unused
    - whitespace
    - zerologlint
    - sqlclosecheck
issues:
  exclude-use-default: false
  fix: true
