---
name: "Feature Request"
description: "Submit a feature request for the current release"
labels: ["feature-request"]
body:
  - type: textarea
    id: problem-statement
    attributes:
      label: What is the problem you are trying to solve with this feature?
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  - type: textarea
    id: feature-solution
    attributes:
      label: What is the solution you are proposing?
      placeholder: A clear and concise description of what you want to happen.
  - type: textarea
    id: feature-alternatives
    attributes:
      label: What alternatives have you considered?
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: feature-details
    attributes:
      label: Additional context
      placeholder: Add any other context or screenshots about the feature request here.
  - type: checkboxes
    id: checks
    attributes:
      label: Contributions
      description: Please confirm the following
      options:
        - label: I have searched through existing issues and feature requests to see if my idea has already been proposed.
          required: true
        - label: If this feature is accepted, I would be willing to help implement and maintain this feature.
          required: false
        - label: If this feature is accepted, I'm willing to sponsor the development of this feature.
          required: false
